version: "3"

services:
  api:
    image: registry:latest
    container_name: registry-api
    restart: always
    ports:
    - "5000:5000"
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /volumes/registry/auth:/auth
      - /volumes/registry/images:/var/lib/registry
    networks:
      - application-network

  client:
    image: joxit/docker-registry-ui:latest
    container_name: registry-client
    restart: always
    ports:
      - "3000:80"
    environment:
      - REGISTRY_TITLE=Amirhossein Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry-api:5000
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true
    networks:
      - application-network

networks:
  application-network:
    external: true
